version: '2.0'

services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - '6379:6379'

volumes:
  database:
